### ISSUE TITLE
Make sure "More info" for cities only shows up when a Pleiades link is available

### ISSUE THREAD

**Issue by pletcher** [inscriptions-israel-palestine/iip-backend#1]
This should be fixed by https://github.com/pletcher/iip-frontend/commit/a541bb318044d9dbaca99e2621a4b3d364783ee8#diff-172468f94da6c5fdda489e0ae5508dd83e06cc9dfd37c03f56cd6213a0740221R198.

**Comment by pletcher** [comment]
@cmroughan, could you confirm this fix when you get a chance?

**Comment by cmroughan** [comment]
Looks good! I'm noticing one small bug (again caused by an issue in the underlying data): when the Pleiades link is entered differently for a city across inscriptions, we seem to get duplicates. (E.g. there are multiple 'Jerusalem's in the list, one whose Pleiades link is an erroneous https://pleiades.stoa.org/places/ without an identifier. We'll get that corrected in the underlying data.

**Comment by pletcher** [comment]
Okay, got it. I'm going to close this issue as fixed, but feel free to open another one.

The reason that this has happened is because of extra spaces in the Epidoc:

```
iip_search_dev=# select id, placename from cities where placename ilike '%Jerusalem%';

 id | placename
----+------------
  7 | Jerusalem
 43 | Jerusalem
 50 |  Jerusalem
```

This is something that I should fix in the ingestion script. I'll open another issue for that.
