### ISSUE TITLE
Display lineated transcriptions in search table

### ISSUE THREAD

**Issue by pletcher** [inscriptions-israel-palestine/iip-backend#8]
From Christine:

> It seems our transcription conventions aren't coming through in the search results page -- for example, on the results page MUQA0002's transcription displays as:
+ Ὑπὲρ σο τη ρίας Θ ωμᾶ δηακόνου. κα ὶ σῶσον αὐτὸν κὲ πάντα τὸν τόπον ἐπι καλούμενον ὸ ἅ γιον α ὐτοῦ.” Α Α ἀμήν. +
instead of:
+ Ὑπὲρ σο[τη]-
ρίας Θ[ω]μᾶ
δηακόνου. κα[ὶ]
σῶσον αὐτὸν κὲ
πάντα τὸν τόπον ἐπι-
καλούμενον ὸ ἅ-
γιον α[ὐ]τοῦ.”
Α Α ἀμήν. +
(In this case, the relevant XML tag behind the [brackets] is <supplied>.)

**Comment by cmroughan** [comment]
This does indeed look to be resolved! Now that the transcriptions and translations in the search results are using the TEI-styled CSS, we might update the display of the placeholder [no transcription] and [no translation] so that the margins don't differ so dramatically between placeholders and transcriptions/translations, but that's not super pressing.
